# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1f95cabd9c21548c3acc0775ccb463ff9a4f0e063603b8cd296d8dc8a4520a1b45161cb7f73f55750615d3e70dc155498da0e4b2ffe4977d0b9f767c22b3f5

test:
  secret_key_base: 0b3d2c473161de3788cc33286d084d0cfef2ea3d93f8be4028358125b96224fdf166ddd690366beb3474a5fff9e5e3ecf82a7d3184cec706f3485b89259b05fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
